### ISSUE TITLE
Something wrong about the incident angle

### ISSUE THREAD

**Issue by HalleyChen** [evanwang13/Metagrating-Topology-Optimization#1]
If incident angle, OptParm.Input.Theta , in initialize.m is not equal to zero, there will be errors on line 146 or line 162 in OptimizeDevice.m

**Comment by evanwang13** [comment]
Error was occurring because the example period calculation did not account for non-zero incidence angles. As a result, the structure did not have the targeted diffraction order. Updated default period calculation in RunOpt.m to better handle changes to incidence angle.
