### ISSUE TITLE
Questions on gradient calculation

### ISSUE THREAD

**Issue by Yunhui-Gao** [evanwang13/Metagrating-Topology-Optimization#3]
Hi,

Thank you for sharing this awesome code :)

I am trying to modify it for another application. But I am not an expert in nanophotonics and I'm having difficulty understanding the gradient calculation steps in OptimizeDevice.m. According to the Nano-Letters paper, the gradient of FoM with respect to the refractive index distribution should be proportional to 
$$\mathrm{Re} ( \mathrm{conj} (t) \mathbf{E}(\mathbf{r}_1) \cdot \mathbf{E}_a (\mathbf{r}_1) ), $$
where E_a denotes the adjoint field. In the Matlab code, the inner product between the forward field and the adjoint field is multiplied by three additional terms, namely the refractive index, one minus absolute efficiency, and $-1i$, which are highlighted below. So I am wondering if these three terms are related to the calculation of the transmission $t$, or are they some kind of modification to the original gradient for better algorithmic performance?

![code](https://user-images.githubusercontent.com/49736381/173064022-fac0d1cc-66a1-425d-854e-c66772862608.png)

I've also tried to check the gradient calculation by introducing a small perturbation to the refractive index distribution, but it doesn't work well. I am not sure whether it is because the gradient is by nature an averaged approximation, or there's something wrong with my code, though.

**Comment by YifengGao666** [comment]
Hi, I have exactly the same question as @Yunhui-Gao mentioned above. 

Could you explain the details of gradient calculation? Thanks a lot!

> Hi,
> 
> Thank you for sharing this awesome code :)
> 
> I am trying to modify it for another application. But I am not an expert in nanophotonics and I'm having difficulty understanding the gradient calculation steps in OptimizeDevice.m. According to the Nano-Letters paper, the gradient of FoM with respect to the refractive index distribution should be proportional to Re(conj(t)E(r1)⋅Ea(r1)), where E_a denotes the adjoint field. In the Matlab code, the inner product between the forward field and the adjoint field is multiplied by three additional terms, namely the refractive index, one minus absolute efficiency, and −1i, which are highlighted below. So I am wondering if these three terms are related to the calculation of the transmission t, or are they some kind of modification to the original gradient for better algorithmic performance?
> 
> ![code](https://user-images.githubusercontent.com/49736381/173064022-fac0d1cc-66a1-425d-854e-c66772862608.png)
> 
> I've also tried to check the gradient calculation by introducing a small perturbation to the refractive index distribution, but it doesn't work well. I am not sure whether it is because the gradient is by nature an averaged approximation, or there's something wrong with my code, though.

**Comment by dalehao** [comment]
Hi , in the repository Metagrating-Topology-Optimization/OptimizeDevice.m, line 150 and 166 . the normalization for TE is sqrt(2/3) and TM is (3/2)*sqrt(2/3) .Where's the normalization constant come from?  
Please help ! THX.
